version: 2.1

jobs:
  build:
    working_directory: ~/rest-exercise

    docker:
      - image: cimg/openjdk:17.0.1

    steps:
      - checkout

      - restore_cache:
          key: rest-exercise-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: rest-exercise-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/rest-exercise-0.0.1-SNAPSHOT.jar

workflows:
  main:
    jobs:
      - build